### ISSUE TITLE
Scopes and Modules

### ISSUE THREAD

**Issue by tanchuev** [vanlooverenkoen/kiwi#6]
What about scopes and modules for dependencies? 

I what to clear few dependencies by calling one method. How can I do it?

Can I create module for some features? Example: AppModule(only app dependencies), ShopListModule, WaletModule...

**Comment by letsar** [comment]
Oh I see, I didn't add this feature. If I let you create as many Containers as you want, is it good enough?

**Comment by vanlooverenkoen** [comment]
Right now you can already create scoped containers. 

```
  final container1 = KiwiContainer.scoped();
  final container2 = KiwiContainer.scoped();
  container1.registerInstance('TEST CONTAINER 1');
  container2.registerInstance('TEST CONTAINER 2');
  container2.registerInstance('TEST CONTAINER 2 NAMED', name: 'named');
```

@5turman  & @tanchuev I think this issue is solved for kiwi. the kiwi_generator is not yet supported but we will take that up in #19  (closing this issue for now. please comment, reopen if you are still having trouble with the current implementation)
